// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdtJ-Fwi85zbytbpmCMPqzJwlB0aJ-lIw',
    appId: '1:1084766332350:web:de3bf9a6bc9d68be0fc5ef',
    messagingSenderId: '1084766332350',
    projectId: 'biometric-attendance-b1353',
    authDomain: 'biometric-attendance-b1353.firebaseapp.com',
    storageBucket: 'biometric-attendance-b1353.appspot.com',
    measurementId: 'G-1NVHBZSX7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFf-epEkCjk5sR9SuZvhONSFtbF95Yss',
    appId: '1:17341946638:android:148f9979e7de39dba7555f',
    messagingSenderId: '17341946638',
    projectId: 'identify-attendance-app',
    storageBucket: 'identify-attendance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq23QNYO93wa1MGEk8-awEuuJ_dn7ajDg',
    appId: '1:17341946638:ios:f4b2543e4311ee24a7555f',
    messagingSenderId: '17341946638',
    projectId: 'identify-attendance-app',
    storageBucket: 'identify-attendance-app.appspot.com',
    iosBundleId: 'com.example.identifyAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSHeqCyBccBoN5xdZc27C87_qCvrtRuQ',
    appId: '1:1084766332350:ios:d2f121e44d1c7bdf0fc5ef',
    messagingSenderId: '1084766332350',
    projectId: 'biometric-attendance-b1353',
    storageBucket: 'biometric-attendance-b1353.appspot.com',
    iosBundleId: 'com.example.unibenCscAttendanceApp.RunnerTests',
  );
}